# Generated by Django 6.0.4 on 2026-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
